/* Generated by `rayfold gen kotlin`. Do not edit. */
package keel.signoff.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Page<T>(val items: List<T>, val cursor: String? = null, val hasMore: Boolean, val total: Int? = null)

@Serializable
data class PageArgs(val first: Int = 20, val after: String? = null, val offset: Int? = null)

@Serializable
data class Member(
    @SerialName("\$type") val type: String = "Member",
    val id: String,
    val name: String,
)

@Serializable
enum class Decision { pending, approved, declined, withdrawn }

/** One sign-off. Read by the team; asked by anyone; decided by the one person it was asked of. */
@Serializable
data class Approval(
    @SerialName("\$type") val type: String = "Approval",
    val id: String,
    val documentId: String,
    val projectId: String,
    /** The document's name when the sign-off was asked, so a list reads without asking the documents service. */
    val documentName: String,
    /** The version asked about. A newer one kept since makes a pending sign-off stale. */
    val version: Int,
    val requester: Member,
    val approver: Member,
    val decision: Decision,
    val note: String? = null,
    /** True once the document has moved on from the version this was asked about, while still pending. */
    val stale: Boolean,
    val askedAt: String,
    val decidedAt: String? = null,
)

@Serializable
data class NotFound(
    val id: String,
)

/** The caller is not the person this sign-off was asked of, or not the one who asked. */
@Serializable
data class NotYours(
    val id: String,
)

@Serializable
data class AlreadyDecided(
    val id: String,
    val decision: Decision,
)

@Serializable
data class ApprovalRequested(
    val approvalId: String,
    val documentId: String,
    val projectId: String,
    val documentName: String,
    val requesterId: String,
    val approverId: String,
)

@Serializable
data class ApprovalDecided(
    val approvalId: String,
    val documentId: String,
    val projectId: String,
    val documentName: String,
    val decision: Decision,
    val byId: String,
    val note: String? = null,
)

/** Raised by the documents service and heard here: a pending sign-off on an older version is stale from then on, when the
bytes changed. A new name on the same bytes (`revision: false`) leaves it as it is. */
@Serializable
data class DocumentChanged(
    val documentId: String,
    val projectId: String,
    val name: String,
    val version: Int,
    val byId: String,
    val revision: Boolean? = null,
)

/** Operation names, kinds and argument classes. */
object Ops {
    const val APPROVAL = "approval"
    @Serializable
    data class ApprovalArgs(
        val id: String,
    )
    const val APPROVALS = "approvals"
    @Serializable
    data class ApprovalsArgs(
        val documentId: String,
    )
    const val INBOX = "inbox"
    const val MEMBERS = "members"
    const val REQUESTAPPROVAL = "requestApproval"
    @Serializable
    data class RequestApprovalArgs(
        val documentId: String,
        val projectId: String,
        val documentName: String,
        val version: Int,
        val approverId: String,
    )
    const val DECIDE = "decide"
    @Serializable
    data class DecideArgs(
        val id: String,
        val decision: Decision,
        val note: String? = null,
    )
    const val WITHDRAW = "withdraw"
    @Serializable
    data class WithdrawArgs(
        val id: String,
    )
}

val OP_KINDS: Map<String, String> = mapOf("approval" to "query", "approvals" to "query", "inbox" to "query", "members" to "query", "requestApproval" to "command", "decide" to "command", "withdraw" to "command")
